### ISSUE TITLE
Custom Fitering not working Properly

### ISSUE THREAD

**Issue by CentralLinks17** [VJBots/VJ-FILTER-BOT#123]
While using the custom filter like year languages quality, it doesn't check the caption. only it check filename and couldn't find the exact results due to the special charcters like for Tam filename will be [tam it skips the selection

make Language short code to large code
Example: [Tam or Tam avaiable na tell to give result for Tamil

**Comment by VJBots** [comment]
Solved Now, But You Have To Add New Mongodb And Index File Again.
Fork My Latest Commit
