### ISSUE TITLE
Some files are not showed up

### ISSUE THREAD

**Issue by Thiyaku17** [VJBots/VJ-FILTER-BOT#129]
The issue is the files gets saved to database, but i searched the same name its not showing up. IDK why? I tried deleting that file and re-add the file and it showed up like the file is already in databases. i couldn't do the deletions also. if i send the file to the delete channel it shows as file not found in database. I just checked the database collection also, the filename is there but its not showed in the get search results.

**Comment by VJBots** [comment]
Now solved , and not search too copy filename search only one or two word

**Comment by CentralLinks17** [comment]
Can you share me the Telegram ID. Still the issue is not fixed. I'll explain with screenshot
