### ISSUE TITLE
Output not showing up when using shortener 

### ISSUE THREAD

**Issue by CentralLinks17** [VJBots/VJ-FILTER-BOT#131]
Bro...if the user sends the start commands to the bot from the buttons or directly in the bot chat ... They weren't able to get the commands to start ... Nothing is replied ... I'll share the video...if you allow me

**Comment by CentralLinks17** [comment]
I got to know that...the error is due to the forcesub ... Try to fix it

**Comment by CentralLinks17** [comment]
Please Fix Force Sub Feature

**Comment by VJBots** [comment]
Now Everything Fixed Now , use latest repo of today

**Comment by CentralLinks17** [comment]
Forcesub issue is not rectified
