### ISSUE TITLE
File Not Found Error Due to Square Braces in File Names

### ISSUE THREAD

**Issue by CentralLinks17** [VJBots/VJ-FILTER-BOT#83]
Description

When a file name includes a language code within square braces (e.g., `[Tam]`, `[Mal]`, `[Hin]`), the system fails to locate the requested file and returns a "NO FILE FOUND" error. The files do exist in the database, but the presence of square braces in the file names is causing this issue.

Steps to Reproduce:
1. Request a file with a name format that includes square braces around the language code, such as `[Tam]`, `[Mal]`, `[Hin]`.
2. Observe that the system returns a "NO FILE FOUND" error.

Expected Behavior:
The system should locate and return the requested file, regardless of the presence of square braces in the file name.

Suggested Fix:
Remove only the square braces from the file names, leaving the language codes intact. This adjustment should be applied to file names, as well as season and episode names, to resolve the issue.

Additional Information
The same issue persists for season and episode names that include square braces.

**Comment by VJBots** [comment]
I will solve it.

**Comment by CentralLinks17** [comment]
I Stated some issues in GitHub...try to rectify it
